#!/bin/bash
# shellcheck disable=SC2086

log_enter pENV

source sENV.sh


export PROJ_LABEL=$SYS
export PROJ_NET=$SYS_NET

export PROJ_CONT=$FREE_CONT
export PROJ_CONT_DATA_DIR=$FREE_DATA_DIR
export PROJ_CONT_DIR=$FREE_CONT_DIR
export PROJ_CONT_HOME_DIR=$FREE_CONT_HOME_DIR
export PROJ_HOST=$FREE_HOST
export PROJ_HOST_DIR=$FREE_HOST_DIR
export PROJ_IMG=$FREE_IMG
export PROJ_PASSWORD=$FREE_PASSWORD
export PROJ_PORT_EXT=$FREE_PORT_EXT
export PROJ_PORT_INT=$FREE_PORT_INT
export PROJ_USER=$FREE_USER
export PROJ_VOL=$FREE_VOL
export PROJ_VOL_DIR=$FREE_VOL_DIR

export PROJ_SYSCTL=$FREE_SYSCTL
export PROJ_CONT_GRP_DIR=$FREE_CONT_GRP_DIR
export PROJ_HOST_GRP_DIR=$FREE_HOST_GRP_DIR


log_exit pENV