@echo off


CALL LOG_ENTER pENV_MOD

CALL sENV

SET "PROJ_HOST=%FREE_HOST%"
SET "PROJ_PASSWORD=%FREE_PASSWORD%"
SET "PROJ_PORT_EXT=%FREE_PORT_EXT%"
SET "PROJ_USER=%FREE_USER%"

SET "PROJ_CONT_GRP_DIR=%FREE_CONT_GRP_DIR%"
SET "PROJ_DOMAIN=%FREE_DOMAIN%"
SET "PROJ_HOST_GRP_DIR=%FREE_HOST_GRP_DIR%"
SET "PROJ_SYSCTL=%FREE_SYSCTL%"

CALL LOG_EXIT pENV_MOD

