@echo off


call LOG_ENTER pENV

CALL sENV

SET "PROJ_LABEL=%SYS%"
SET "PROJ_NET=%SYS_NET%"

SET "PROJ_CONT=%FREE_CONT%"
SET "PROJ_CONT_DATA_DIR=%FREE_CONT_DATA_DIR%"
SET "PROJ_CONT_DIR=%FREE_CONT_DIR%"
SET "PROJ_CONT_HOME_DIR=%FREE_CONT_HOME_DIR%"
SET "PROJ_HOST=%FREE_HOST%"
SET "PROJ_HOST_DIR=%FREE_HOST_DIR%"
SET "PROJ_IMG=%FREE_IMG%"
SET "PROJ_PASSWORD=%FREE_PASSWORD%"
SET "PROJ_PORT_EXT=%FREE_PORT_EXT%"
SET "PROJ_PORT_INT=%FREE_PORT_INT%"
SET "PROJ_USER=%FREE_USER%"
SET "PROJ_VOL=%FREE_VOL%"
SET "PROJ_VOL_DIR=%FREE_VOL_DIR%"

call LOG_EXIT pENV
