FROM freeipa/freeipa-server:centos-8

# https://docker-repo-nexus.dev.ccg-gcc.gc.ca

USER root

EXPOSE 8080

ARG HOME

RUN mkdir -p $HOME
WORKDIR ${HOME}

RUN apt install policycoreutils
RUN setsebool -P container_manage_cgroup 1
RUN setsebool: SELinux is disabled.


